<style type="text/css">
body {
	font-family: arial,helvetica,sans;
	font-size: 11px;
}
table {
	border-width: 1px 1px 1px 1px;
	border-spacing: 2px;
	border-style: solid solid solid solid;
	border-color: gray gray gray gray;
	border-collapse: collapse;
	background-color: white;
	cell-padding: 3;
}
table th {
	border-width: 1px 1px 1px 1px;
	padding: 2px 2px 2px 2px;
	border-style: solid solid solid solid;
	border-color: gray gray gray gray;
	background-color: white;
	-moz-border-radius: 0px 0px 0px 0px;
}
table td {
	border-width: 1px 1px 1px 1px;
	padding: 2px 2px 2px 2px;
	border-style: solid solid solid solid;
	border-color: gray gray gray gray;
	background-color: white;
	-moz-border-radius: 0px 0px 0px 0px;
}

table  tr.d0 td {
	background-color: #FCF6CF;
}
table  tr.d1 td {
	background-color: #FEFEF2;
}

</style>