<p>
    <a href="index.html">Home</a> |
	<a href="bond_tracking.php">Track Bonds</a> |
	<a href="bond_redemption.php">Redeem Bonds</a> |
	<a href="manage_bills.php">Manage Bills</a> |
	<a href="manage_staff.php">Manage Staff</a> |
	<a href="manage_events.php">Manage Events</a> |
	<a href="manage_businesses.php">Manage Businesses</a> |
	<a href="manage_employees.php">Manage Employees</a> |
	<a href="manage_checks.php">Manage Checks</a> |
	<a href="reports.php">Reports</a>
</p>
